# dependabot
# This file is part of the pgRouting project.
# Copyright (c) 2022-2026 pgRouting developers
# License: GPL-2 See https://github.com/pgRouting/pgrouting/blob/main/LICENSE

version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  target-branch: main

#develop branch starts here
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "weekly"
  target-branch: develop
