# ------------------------------------------------------------------------------
# Travis CI scripts 
# Copyright(c) pgRouting Contributors
#
# Main configuration
# ------------------------------------------------------------------------------

language: c

sudo: required

compiler:
  - gcc

notifications:
  email:
    on_failure: project@pgrouting.org

branches:
  only:
    - master
    - develop
    - new-travis-dev-2.2

addons:
  postgresql: "9.2"
  postgresql: "9.3"
  postgresql: "9.4"

services:
  #- postgresql: 9.1
  #- postgresql: 9.2
  #- postgresql: 9.3

env:
  matrix:
    - POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.1
    - POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1
    - POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    - POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1

    - POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.0
    - POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.0
    - POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0
    - POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0

    ## We are NOT supporting these for pgrouting 2.1.0
    #- POSTGRESQL_VERSION=8.4 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.0 POSTGIS_VERSION=1.5
    #- POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5

install:
  - ./tools/travis/pgrouting_install.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

before_script:
  #-

script: 
  - ./tools/travis/pgrouting_build.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_script: 
  - ./tools/travis/pgrouting_prepare.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
  - ./tools/travis/pgrouting_test.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

after_success:
  #- ./tools/travis/pgrouting_deploy.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

