language: c

compiler:
  - gcc

notifications:
  email:
    on_failure: project@pgrouting.org

branches:
  only:
    - develop

services:
  - postgresql

env:
  - POSTGIS_VERSION=1.5
  - POSTGIS_VERSION=2

install:
  # Add PPA for PostGIS 2.x
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then sudo apt-add-repository -y ppa:ubuntugis/ubuntugis-unstable; fi

  # Add PPA for pgRouting Travis
  - sudo apt-add-repository -y ppa:georepublic/pgrouting-travis
  - sudo apt-get -q update

  # Install dependecies
  - sudo apt-get install -q cmake libcgal-dev libboost-graph-dev libboost-thread-dev postgresql-server-dev-all

  # Install PostGIS
  - sudo apt-get install -q postgresql-9.1-postgis

before_script:
  # Create database user "gis"
  - psql -c "CREATE ROLE gis PASSWORD 'gis' SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres

  # Create database "gis"
  - psql -c 'CREATE DATABASE gis;' -U postgres

  # Add PostGIS extension to "gis" database
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-1.5/postgis.sql; fi
  - if [[ "$POSTGIS_VERSION" == "1.5" ]]; then psql -d gis -U postgres -f /usr/share/postgresql/9.1/contrib/postgis-1.5/spatial_ref_sys.sql; fi
  - if [[ "$POSTGIS_VERSION" != "1.5" ]]; then psql -d gis -U postgres -c "CREATE EXTENSION postgis;"; fi

script: 
  - cmake -DWITH_DD=ON
  - make
  - sudo make install

after_script:
  # Test pgRouting
  - psql -U postgres -d gis -c "CREATE EXTENSION pgrouting;"
  - tools/test-runner.pl

