name: Check files

on:
  push:
    branches-ignore:
      - 'translations_*'
    tag:
    pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          releases: ["(2.6.0 2.6.1 2.6.2 2.6.3)","(3.0.0 3.0.1 3.0.2)"]
          os: [ubuntu-latest]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Signature files do not change within same minor
        run: |
          tempvar=$(echo "${{ matrix.releases }}")
          RELEASE=(${tempvar//[\(\)]/})
          for value in "${RELEASE[@]}"; do
            if [ "$value" == "${RELEASE[0]}" ]; then continue; fi
            diff "sql/sigs/pgrouting--${value}.sig" "sql/sigs/pgrouting--${RELEASE[0]}.sig" | wc -l | grep 4
          done

      - name: News file up to date
        run: |
          tools/release-scripts/notes2news.pl
          ! git status | grep 'NEWS'
