name: Check queries

on:
  push:
    branches-ignore:
      - 'translations_*'
    tags: []
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          psql: [12]
          postgis: [3]
          os: [ubuntu-latest]

    steps:
      - name: Add PostgreSQL APT repository
        run: |
          sudo apt-get install curl ca-certificates gnupg
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ \
            $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libboost-graph-dev \
            libtap-parser-sourcehandler-pgtap-perl \
            postgresql-${{ matrix.psql }} \
            postgresql-${{ matrix.psql }}-pgtap \
            postgresql-${{ matrix.psql }}-postgis-${{ matrix.postgis }} \
            postgresql-${{ matrix.psql }}-postgis-${{ matrix.postgis }}-scripts \
            postgresql-server-dev-${{ matrix.psql }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure
        run: |
          export PATH=/usr/lib/postgresql/${{ matrix.psql }}/bin:$PATH
          mkdir build
          cd build
          cmake -DPOSTGRESQL_VERSION=${{ matrix.psql }} -DCMAKE_BUILD_TYPE=Debug ..

      - name: Build
        run: |
          cd build
          make -j 4
          sudo make install

      - name: Test signature is up to date
        run: |
          sudo service postgresql start
          PGPORT=5433
          if [ "${{ matrix.psql }}" == "12" ]; then PGPORT=5432; fi
          sudo -u postgres createdb -p ${PGPORT}  ____sigs_routing____
          sudo -u postgres psql -c "CREATE ROLE runner SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN" -d ____sigs_routing____
          sh tools/release-scripts/get_signatures.sh -p ${PGPORT}
          git diff --exit-code --quiet sql/sigs/*.sig

      - name: Test documentation queries are up to date
        run: |
          #sudo service postgresql start
          #PGPORT=5433
          #if [ "${{ matrix.psql }}" == "12" ]; then PGPORT=5432; fi
          PGPORT=5433
          if [ "${{ matrix.psql }}" == "12" ]; then PGPORT=5432; fi
          sudo -u postgres createdb -p ${PGPORT}  pgr_test__db__test
          TESTDIRS="version"
          for d in ${TESTDIRS}
          do
            ./tools/testers/doc_queries_generator.pl -pgver "${{ matrix.psql }}" -pguser runner -documentation -alg "${d}"
          done

          ./tools/testers/doc_queries_generator.pl -pgver "${{ matrix.psql }}"
